### ISSUE TITLE
Dashboard card: absent people

### ISSUE THREAD

**Issue by kelvinst** [0ks/blessd_umbrella#46]
The idea is a box with the top 5 most absent people, ordered by the quantity of repeated absences. There should also be a link for another page with the complete list of absent people, and also a person details page, with this person info and a presence board, maybe something like Github's contribution calendar.

PS.: Only public meetings and members should count for this absent people list.

**Comment by mingyar** [comment]
A short brief solution:

In order to rank people, the rotine will consider the total number of abesences not considering people that was present on the last meting.

I guess that could be done in just on select statement.

**Comment by kelvinst** [comment]
Just to mention I'm working on it... Since it's kind of complex 👍

**Comment by mingyar** [comment]
Ok bud, no problem, go ahead and make it.

I'll be working on that presentation stuff that we've been discussed, I
believe that I'll add more value doing that, because is not that complex 😉
