### ISSUE TITLE
First signup | People view blows up

### ISSUE THREAD

**Issue by mingyar** [0ks/blessd_umbrella#53]
**Describe the bug**
After signup as a new church, trying to access access People menu item it comes with an error.

**To Reproduce**
1. Do a Signup as new church;
2. Click on 'People

**Expected behavior**
Open the people view.

**Screenshots**
![image](https://user-images.githubusercontent.com/1013248/50047721-5c045300-00a2-11e9-9e69-6f2b0c19a2de.png)

**Comment by kelvinst** [comment]
You just forgot to run `mix ecto:migrate`

**Comment by mingyar** [comment]
Ok! I'll do it! Thanks bud!
